### ISSUE TITLE
Feature Request: Datatype logged data

### ISSUE THREAD

**Issue by Mailblocker** [Sensirion/SmartGadget-Firmware#3]
Hello,
as far as I understand from the code the logged data (humidity and temperature) is stored in datatype float. Wouldn't it be more storage efficient to use int16_t and a scaling to do this?

e.g.:
Temperature is multipled by 100 this means a range of -327.68°C to 327.67°C can be saved with a resolution of 0.01K. 
Humidity is multipled by 100 resulting in a range of the same but not needed. Resultion would be also 0.01%.

The whole change would result in being able to store twice the data respectively double the time at the same logging interval.

**Comment by abrauchli** [comment]
Hi @Mailblocker,
[edit - sorry, I thought the comment was on the SmartGadget Android App]
Thanks for your interest. Your assumption seems correct, I am however not certain that this Firmware is still maintained for feature development. I'll be sure to forward any patches if you feel like patching that - closing the issue for now though.

**Comment by Mailblocker** [comment]
Alright, just to mention I wasn't talking about the storage on the app side. I was talking about the flash memory of the nordic µC to enlarge the logging interval until the data has to be collected via BLE.

edit: Just saw your edit :-D Yeah I was talking about the µC.

**Comment by kizniche** [comment]
Hello. I am developing software that utilizes this device and would like to perform a check that the user options for logging interval and download interval don't exceed the memory of the device. Could you please help me understand the maximum number of measurements that can be stored? I haven't come across the pertinent documentation for this and would greatly appreciate the help.

Thank you

**Comment by Mailblocker** [comment]
Hi kizniche,
I'm not a developer of this software but I'm able to give a few hints since I dug through the code.

With RingBuffer.h line 77
```
enum privateConstants
{
    NRF51822_PAGESIZE_BYTES = 1024,
    BYTES_PER_VALUE = 4
};
```
and Logger.h line 147
```
  enum privateConstants
  {
    NRF51822_NUMBER_OF_FLASH_PAGES = 256, //nRF51822-xxAA
#if (0 == NEED_CONSOLE_OUTPUT)
    NRF51822_FLASH_PAGES_USED = 127, //Adjust if application code + softdevice size exceeds 128kB
#else
    NRF51822_FLASH_PAGES_USED = 145,//140,//135, //Adjust if application code + softdevice size exceeds 128kB
#endif
    MAX_REGISTERED_SERVICES = 2,
    INDEXING_ERROR = 0xFFFF
  };
```

You get the size of the buffer the device is able to provide for data logging (4 Bytes per Value so 8 Bytes for temperature and humidity).
So it should be for NEED_CONSOLE_OUTPUT = 0
(256-127) * 1024 / (4 * 2) = 16512

for NEED_CONSOLE_OUTPUT != 0
(256-145) * 1024 / (4 * 2) = 14208
