### ISSUE TITLE
Smart Gadget Raspberry Pi connect

### ISSUE THREAD

**Issue by eap904** [Sensirion/SmartGadget-Firmware#4]
Hi, 

This isn't really an issue per-se, but I am looking for information about connecting this gadget to a raspberry pi via BLE. Any info to point me in the right direction, greatly appreciated. 

Thanks

**Comment by abrauchli** [comment]
Hi @eap904 
I'd say that depends heavily on what OS is running on your raspberry. If you're running Linux you can use bluez to connect but we don't have a how-to guide yet - that'd be really nice to have, but I don't think we'll get to it anytime soon.

If you're using python I started a bluez integration in https://github.com/peplin/pygatt/pull/95 for that exact purpose but it was left unfinished - though I was able to subscribe to the gadget.. It's open source, feel free to complete it.

For your convenicence I just published the last state of the project.
https://github.com/abrauchli/python-smartgadget
Disclaimer: it's all work-in-progress that's not in progress anymore. I/We can't support it but if you have contributions I'm happy to merge pull-requests.

Not an issue, closing.

**Comment by rnestler** [comment]
Hi @eap904 
I once connected to a SHTC1 SmartGadget using bluez on Linux: https://rnestler.github.io/reading-the-shtc1-smart-gadget-ble-device.html
Hope this helps.

**Comment by eap904** [comment]
Hi @rnestler !

Yes that helps greatly. I am able to successfully make a connection using bluetoothctl, but the connection with gatttool fails. I do not see a command for reading the UUID address with bluetoothctl. But I will keep trying!

Once connected, I will have to figure out how to make the pi automatically connect to the device, and then figure out how to poll the device using the Mycodo software. Thank you again

**Comment by kizniche** [comment]
@eap904 Have you attempted to use the UUIDs from https://github.com/Sensirion/SmartGadget-Firmware/raw/master/Simple_BLE_Profile_Description.pdf ?

**Comment by eap904** [comment]
I was able to successfully connect with the device, and I think even trust and pair it..  still learning about bluetooth as I go. I was having problems with running the char-read command.
