### ISSUE TITLE
Button Interrupt Service Routine 

### ISSUE THREAD

**Issue by pascalenderli** [Sensirion/SmartGadget-Firmware#5]
I am playing around with your firmware and programmed the button to switch between different program modes.
The custom functions which are executed need more time than the original function which is implemented in the periodic callback:

```cpp
//in SmartGatget.cpp
void SmartGadget::periodicCallback(void* p_context) 
{ 
  // ...
  processSensorDataAndStartNewMeasurement();
  //...
}
```

The problem I face using the described setting is the following:
Pressing the button has no influence anymore (but should actually switch to next program mode). I suppose it is because my custom functions do not return within a timer cycle anymore. I guess timer interrupts have priority before button interrupts and therefore the button interrupt is never executed?

I have this assumption because everything works well if I replace my function by `wait_ms(t)` for small t, but it starts struggling when t is getting bigger. So implementation of the button press context switch itself works actually very well.

Also my custom function work well if they run in single mode from startup.

I tried to play around with `ADVERTISING_INTERVAL_0MS625` and `PERIODIC_CALLBACK_INTERVAL_MS` in SmartGatget.h which had no influence on the program at all.
Timing is not important for me.

I would really appreciate if somebody could give me a hint what could solve the problem.

**Comment by pascalenderli** [comment]
The timer interval can be changed as defined in _app_timer.h_ using the definitions of:
```c
#define APP_TIMER_TICKS(MS, PRESCALER) ( ... )
// and:
uint32_t app_timer_start(app_timer_id_t timer_id, uint32_t timeout_ticks, void * p_context);
```

the functions need to be modified in _SmartGatget.h_ `void SmartGadget::init(void)` as follows:
`
```cpp
const int pre_scaler = 0;
const int timer_timeout_ms = 1000;
static app_timer_id_t timer_ID;
APP_TIMER_INIT(pre_scaler, 1, 1, false);
app_timer_create( &timer_ID, APP_TIMER_MODE_REPEATED, static_cast<app_timer_timeout_handler_t>(periodicCallback) );
app_timer_start( timer_ID, APP_TIMER_TICKS(timer_timeout_ms, pre_scaler), NULL );
```
make sure you use the same prescaler for `APP_TIMER_TICKS(MS, PRESCALER)` and ` APP_TIMER_INIT(PRESCALER, MAX_TIMERS, OP_QUEUES_SIZE, USE_SCHEDULER)

**Comment by abrauchli** [comment]
Hi @pascalenderli Thanks for updating!
